# Generated by Django 2.0.13 on 2019-05-17 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('imdb', models.DecimalField(decimal_places=2, max_digits=4)),
                ('image', models.CharField(max_length=255)),
            ],
        ),
    ]
